// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRNimsJWyXoMFvpfeidxXHqMun0pJb6es',
    appId: '1:571320088173:web:33ae6490eab6e435bfb164',
    messagingSenderId: '571320088173',
    projectId: 'loh-coffee-eatery',
    authDomain: 'loh-coffee-eatery.firebaseapp.com',
    storageBucket: 'loh-coffee-eatery.appspot.com',
    measurementId: 'G-94KKLEBYSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjTN0aqXnj8migECJQbIEsjOTvZtoAVQ8',
    appId: '1:571320088173:android:dc01bd666473bb8bbfb164',
    messagingSenderId: '571320088173',
    projectId: 'loh-coffee-eatery',
    storageBucket: 'loh-coffee-eatery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRqwlumKddOqyLU_W25_P8cypJ9PQxD0',
    appId: '1:571320088173:ios:0cb17db8cd419f85bfb164',
    messagingSenderId: '571320088173',
    projectId: 'loh-coffee-eatery',
    storageBucket: 'loh-coffee-eatery.appspot.com',
    iosClientId: '571320088173-3b6mnhhjq894fiplq7ifgvoue71j0o53.apps.googleusercontent.com',
    iosBundleId: 'com.example.lohCoffeeEatery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRqwlumKddOqyLU_W25_P8cypJ9PQxD0',
    appId: '1:571320088173:ios:0cb17db8cd419f85bfb164',
    messagingSenderId: '571320088173',
    projectId: 'loh-coffee-eatery',
    storageBucket: 'loh-coffee-eatery.appspot.com',
    iosClientId: '571320088173-3b6mnhhjq894fiplq7ifgvoue71j0o53.apps.googleusercontent.com',
    iosBundleId: 'com.example.lohCoffeeEatery',
  );
}
